INSERT INTO `Posts` (`jobTitle`, `jobDescription`,`jobQualification`,`additionalInfo`, `companyName`, `address`, `city`, `state`, `zipCode`,`placeID`, `latitude`, `longitude`, `createdat`, `updatedat`) VALUES ('Web Developer', 'HTML5, CSS3, Javascript Skills','Required bachelors or masters degree in Computer Science','Must be able to work in California, Colorado, of Washington,DC','Google Inc.', '1600 Amphitheatre Parkway', 'Mountain View', 'CA', '94043', 'ChIJxQvW8wK6j4AR3ukttGy3w2s', '37.4224082','-122.0856086','2018-03-15 18:43:06','2018-03-15 18:43:06');

INSERT INTO `Posts` (`jobTitle`, `jobDescription`,`jobQualification`,`additionalInfo`, `companyName`, `address`, `city`, `state`, `zipCode`, `placeID`,  `latitude`, `longitude`, `createdat`, `updatedat`) VALUES ('Front-End Developer', 'Good Javascript & Python Skills','Required bachelors or masters degree in Computer Science','Must be able to work in California, Colorado, of Washington,DC','Microsoft Visitor Center', '15010 NE 36th St.', 'Redmond', 'WA', '98052', 'ChIJ01cbYm1tkFQR7__hc9koMv0', '47.6423109','-122.13684060000003','2018-03-15 18:43:06','2018-03-15 18:43:06');

INSERT INTO `Posts` (`jobTitle`, `jobDescription`,`jobQualification`,`additionalInfo`, `companyName`, `address`, `city`, `state`, `zipCode`, `placeID`,  `latitude`, `longitude`, `createdat`, `updatedat`) VALUES ('UX-UI Developer', 'Design background, Bootstrap Skills','Required bachelors or masters degree in Computer Science','Must be able to work in California, Colorado, of Washington,DC', 'Esri Headquarters', '380 New York Street', 'Redlands', 'CA', '92373', 'ChIJGSvbtWqq3IARKzExa1oliEA', '34.0560768','-117.19568559999999','2018-03-15 18:43:06','2018-03-15 18:43:06');

INSERT INTO `Posts` (`jobTitle`, `jobDescription`,`jobQualification`,`additionalInfo`, `companyName`, `address`, `city`, `state`, `zipCode`, `placeID`, `latitude`, `longitude`, `createdat`, `updatedat`) VALUES ('Consulting Developer', 'Strong communication skills, Back-end Skills(Node.js,Express.js prefered)','Required bachelors or masters degree in Computer Science','Must be able to work in California, Colorado, of Washington,DC','Brandywine Realty Trust', '3130 Fairview Park Dr', 'Falls Church', 'VA', '22042', 'ChIJ-xemWp9MtokR_rC6lXtvMp8', '38.8605487','-77.21817579999998','2018-03-15 18:43:06','2018-03-15 18:43:06');


INSERT INTO `Posts` (`jobTitle`, `jobDescription`,`jobQualification`,`additionalInfo`, `companyName`, `address`, `city`, `state`, `zipCode`, `placeID`, `latitude`, `longitude`, `createdat`, `updatedat`) VALUES ('Front End Engineer', 'Create interactive Web-based user interface components and data visualizations','Required bachelors or masters degree in Computer Science, Good Javascript & Python Skills','Experience with front office software development within an asset management firm, hedge fund or investment bank','Hays Companies', '1025 Thomas Jefferson St NW', 'Washington', 'DC', '20007', 'ChIJRR-xfEy2t4kRAgPwuA6zJdU', '38.9032492','-77.0597743','2018-03-15 18:43:06','2018-03-15 18:43:06');

INSERT INTO `Posts` (`jobTitle`, `jobDescription`,`jobQualification`,`additionalInfo`, `companyName`, `address`, `city`, `state`, `zipCode`, `placeID`, `latitude`, `longitude`, `createdat`, `updatedat`) VALUES ('Front End Engineer', 'Develop a new section in our Angular 2 web app that allows you to run a full text search against data stored in our AWS hosted Elasticsearch cluster','Required bachelors or masters degree in Computer Science, Good Javascript & Python Skills','Experience with automated delivery pipelines, agile delivery and test-driven development','Harris, Wiltshire & Grannis LLP', '1919 M St NW', 'Washington', 'DC', '20036', 'ChIJ-8jiGLi3t4kRsGXAyUAeU_E', '38.9060257','-77.04448289999999','2018-03-15 18:43:06','2018-03-15 18:43:06');

INSERT INTO `Posts` (`jobTitle`, `jobDescription`,`jobQualification`,`additionalInfo`, `companyName`, `address`, `city`, `state`, `zipCode`, `placeID`, `latitude`, `longitude`, `createdat`, `updatedat`) VALUES ('Front End Engineer', 'Provide support for a range of proprietary and third-party analytical tools and services, along with some third-party applications','Required bachelors or masters degree in Computer Science, Good Javascript & Python Skills','Knowledge of Web development, Web architecture, HTTP, JSON REST, CORS, and JSONP','Thycotic', '1101 17th St NW #1102', 'Washington', 'DC', '20036', 'EjAxMTAxIDE3dGggU3QgTlcgIzExMDIsIFdhc2hpbmd0b24sIERDIDIwMDM2LCBVU0E', '38.9041053','-77.03807549999999','2018-03-15 18:43:06','2018-03-15 18:43:06');

INSERT INTO `Posts` (`jobTitle`, `jobDescription`,`jobQualification`,`additionalInfo`, `companyName`, `address`, `city`, `state`, `zipCode`, `placeID`, `latitude`, `longitude`, `createdat`, `updatedat`) VALUES ('Back End Enginner', 'Write code that contributes to drchronos core product and open APIs','Knowledge and experience with developing front-end applications using JavaScript and a JavaScript framework (e.g. React, AngularJS, Vue, Knockout.js, etc.)','Experience with front office software development within an asset management firm, hedge fund or investment bank','Aquicore', '875 N St NW #205', 'Washington', 'DC', '20001', 'Eis4NzUgTiBTdCBOVyAjMjA1LCBXYXNoaW5ndG9uLCBEQyAyMDAwMSwgVVNB', '38.907378','-77.0237252','2018-03-15 18:43:06','2018-03-15 18:43:06');

INSERT INTO `Posts` (`jobTitle`, `jobDescription`,`jobQualification`,`additionalInfo`, `companyName`, `address`, `city`, `state`, `zipCode`, `placeID`, `latitude`, `longitude`, `createdat`, `updatedat`) VALUES ('Back End Enginner', 'Design & write software to help manage and automate the complexity of running a private medical practice','Knowledge and experience with developing front-end applications using JavaScript and a JavaScript framework (e.g. React, AngularJS, Vue, Knockout.js, etc.)','Experience with automated delivery pipelines, agile delivery and test-driven development','CGI', '1100 New Jersey Ave SE # 800', 'Washington', 'DC', '20003', 'EjYxMTAwIE5ldyBKZXJzZXkgQXZlIFNFICM4MDAsIFdhc2hpbmd0b24sIERDIDIwMDAzLCBVU0E', '38.8770439','-77.0038162','2018-03-15 18:43:06','2018-03-15 18:43:06');

INSERT INTO `Posts` (`jobTitle`, `jobDescription`,`jobQualification`,`additionalInfo`, `companyName`, `address`, `city`, `state`, `zipCode`, `placeID`, `latitude`, `longitude`, `createdat`, `updatedat`) VALUES ('Back End Enginner', 'Implement automated and exploratory testing processes that provide continuous feedback on quality issues; find ways to break our web application before their public release','Knowledge and experience with developing front-end applications using JavaScript and a JavaScript framework (e.g. React, AngularJS, Vue, Knockout.js, etc.)','Knowledge of Web development, Web architecture, HTTP, JSON REST, CORS, and JSONP','ByteCubed', '2231 Crystal Dr #401', 'Arlington', 'VA', '22202', 'Ei4yMjMxIENyeXN0YWwgRHIgIzQwMSwgQXJsaW5ndG9uLCBWQSAyMjIwMiwgVVNB', '38.8538222','-77.0486935','2018-03-15 18:43:06','2018-03-15 18:43:06');

INSERT INTO `Posts` (`jobTitle`, `jobDescription`,`jobQualification`,`additionalInfo`, `companyName`, `address`, `city`, `state`, `zipCode`, `placeID`, `latitude`, `longitude`, `createdat`, `updatedat`) VALUES ('UX-UI Designer', 'Model interactions through process diagrams, task flows and interaction diagrams as needed','Confident communicator with demonstrable ability to argue a point concisely and deal positively with conflicting viewpoints','Knowledge and experience in JavaScript and/or Node.js','Excella Consulting', '2300 Wilson Blvd #630', 'Arlington', 'VA', '22201', 'Ei8yMzAwIFdpbHNvbiBCbHZkICM2MzAsIEFybGluZ3RvbiwgVkEgMjIyMDEsIFVTQQ', '38.8904702','-77.0872272','2018-03-15 18:43:06','2018-03-15 18:43:06');

INSERT INTO `Posts` (`jobTitle`, `jobDescription`,`jobQualification`,`additionalInfo`, `companyName`, `address`, `city`, `state`, `zipCode`, `placeID`, `latitude`, `longitude`, `createdat`, `updatedat`) VALUES ('Senior UX-UI Designer', 'Model interactions through process diagrams, task flows and interaction diagrams as needed','Confident communicator with demonstrable ability to argue a point concisely and deal positively with conflicting viewpoints','Knowledge and experience in JavaScript and/or Node.js','Capitol Technology Solutions', '3321 Georgia Avenue NW, Suite 43909', 'Washington', 'DC', '20010', 'ChIJP6trahvIt4kR5VnxgyESQqg', '38.9316035','-77.0233642','2018-03-15 18:43:06','2018-03-15 18:43:06');

INSERT INTO `Posts` (`jobTitle`, `jobDescription`,`jobQualification`,`additionalInfo`, `companyName`, `address`, `city`, `state`, `zipCode`, `placeID`, `latitude`, `longitude`, `createdat`, `updatedat`) VALUES ('UX-UI Design', 'Model interactions through process diagrams, task flows and interaction diagrams as needed','Confident communicator with demonstrable ability to argue a point concisely and deal positively with conflicting viewpoints','Knowledge and experience in JavaScript and/or Node.js','VisiSonics Corporation', '8201 Corporate Dr # 300', 'Landover', 'MD', '20785', 'EjI4MjAxIENvcnBvcmF0ZSBEciAjMzAwLCBIeWF0dHN2aWxsZSwgTUQgMjA3ODUsIFVTQQ', '38.9460704','-76.8643938','2018-03-15 18:43:06','2018-03-15 18:43:06');

INSERT INTO `Posts` (`jobTitle`, `jobDescription`,`jobQualification`,`additionalInfo`, `companyName`, `address`, `city`, `state`, `zipCode`, `placeID`, `latitude`, `longitude`, `createdat`, `updatedat`) VALUES ('Web Developer', 'Assist with Network Systems (domains, dns records, servers).','Required bachelors or masters degree in Computer Science, Good Javascript & Python Skills','Knowledge and experience in JavaScript and/or Node.js','SRA International Inc', '387 Technology Dr', 'College Park', 'MD', '20742', 'ChIJL7KFK6LGt4kRkBAHt49-3EI', '38.9925244','-76.9387525','2018-03-15 18:43:06','2018-03-15 18:43:06');

INSERT INTO `Posts` (`jobTitle`, `jobDescription`,`jobQualification`,`additionalInfo`, `companyName`, `address`, `city`, `state`, `zipCode`, `placeID`, `latitude`, `longitude`, `createdat`, `updatedat`) VALUES ('Web Developer', 'Work with developers and content producers to ensure websites are optimized for security, speed and accessibility.','Required bachelors or masters degree in Computer Science, Good Javascript & Python Skills','Knowledge and experience in JavaScript and/or Node.js','Intact Technology', '9111 Edmonston Rd', 'Greenbelt', 'MD', '20770', 'ChIJs0RL_ebDt4kRejG8ZQdkE2E', '39.0003979','-76.8980821','2018-03-15 18:43:06','2018-03-15 18:43:06');

INSERT INTO `Posts` (`jobTitle`, `jobDescription`,`jobQualification`,`additionalInfo`, `companyName`, `address`, `city`, `state`, `zipCode`, `placeID`, `latitude`, `longitude`, `createdat`, `updatedat`) VALUES ('UX-UI Developer', 'Design and implement GUI elements for new gameplay features','Knowledge of and experience with at least one CSS framework (e.g. Bootstrap, Foundation, etc.)','Knowledge and experience in JavaScript and/or Node.js','Dev Technology', '11480 Commerce Park Dr Suite 400', 'Reston', 'VA', '20191', 'EjIxMTQ4MCBDb21tZXJjZSBQYXJrIERyICM0MDAsIFJlc3RvbiwgVkEgMjAxOTEsIFVTQQ', '38.9470139','-77.342582399999970','2018-03-15 18:43:06','2018-03-15 18:43:06');

INSERT INTO `Posts` (`jobTitle`, `jobDescription`,`jobQualification`,`additionalInfo`, `companyName`, `address`, `city`, `state`, `zipCode`, `placeID`, `latitude`, `longitude`, `createdat`, `updatedat`) VALUES ('Contract Developer', 'Create assets that maintain and develop the visual identity of current and upcoming titles','Knowledge of and experience with at least one CSS framework (e.g. Bootstrap, Foundation, etc.)','Experience with front office software development within an asset management firm, hedge fund or investment bank','Mobomo', '1600 Spring Hill Rd Suite 300', 'Vienna', 'VA', '22182', 'Ei8xNjAwIFNwcmluZyBIaWxsIFJkICMzMDAsIFZpZW5uYSwgVkEgMjIxODIsIFVTQQ', '38.926598','-77.247748','2018-03-15 18:43:06','2018-03-15 18:43:06');
